### ISSUE TITLE
Add LICENSE to release builds

### ISSUE THREAD

**Issue by kavinzhao** [w568w/DanXi#16]
To comply with open-source software licenses, we need to add a "About" page with all the LICENSE files from those software (and probably together with credits to all the authors).

**Comment by kavinzhao** [comment]
需要一份LICENSE清单。 @KYLN24 能否将所有的LICENSE整理为txt文件发给我？

**Comment by w568w** [comment]
@KYLN24 Licenses 直接加到这里就行了：
https://github.com/w568w/DanXi/blob/256e2174314a7d65fc589ee8940ceeea73f8e4e6/lib/page/subpage_settings.dart#L40

**Comment by kavinzhao** [comment]
> @KYLN24 Licenses 直接加到这里就行了：
> 
> https://github.com/w568w/DanXi/blob/256e2174314a7d65fc589ee8940ceeea73f8e4e6/lib/page/subpage_settings.dart#L40

理论上Licenses不应该以链接形式提供…应该是直接扔文本上去的🤦

参见操作系统的LICENSES页面

**Comment by w568w** [comment]
搞定了
