### ISSUE TITLE
[BUG] 在网络较差时，反复要求用户注册论坛

### ISSUE THREAD

**Issue by w568w** [w568w/DanXi#20]
**Describe the bug**
如题

**To Reproduce**
1. 使用较差的网络（可通过更改 bmob key 来模拟无法联网状态）
2. 打开应用，稍等片刻或自行点击树洞页面
3. 出现注册窗口（无论之前是否注册过）

**Expected behavior**
应当出现网络错误界面，提供方式让用户重试加载

**Comment by w568w** [comment]
该 BUG 严重影响用户体验，在修复前不应该发布 0.1.1 版本。

**Comment by kavinzhao** [comment]
从操作逻辑上看，注册论坛没有要求用户确认的必要，可程序自动完成。

**Comment by w568w** [comment]
> 
> 
> 从操作逻辑上看，注册论坛没有要求用户确认的必要，可程序自动完成。

第一次登录是为了让用户查看用户协议（虽然目前还没有），这个步骤暂时不能隐性完成
