### ISSUE TITLE
[BUG] Crash on switching theme

### ISSUE THREAD

**Issue by w568w** [w568w/DanXi#23]
**Describe the bug**
```
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3697 pos 12: 'element._lifecycleState == _ElementLifecycle.inactive': is not true.

'package:flutter/src/widgets/framework.dart': Failed assertion: line 5576 pos 14: 'oldChild == null || oldChild._lifecycleState == _ElementLifecycle.active': is not true.

Duplicate GlobalKey detected in widget tree.
LateInitializationError: Field '_children@102042623' has not been initialized.
```

**To Reproduce**
1. Go to setting page
2. Change theme once or twice
3. Crash happened

**Smartphone (please complete the following information):**
 - OS: Android 11.0

**Comment by kavinzhao** [comment]
What is this error caused by?

If it's too hard to switch themes on-the-fly (due to widget reloads etc.), maybe we can save user's theme preferences in `SharedPreferences` and set it using `initialPlatform` on application launch.

**Comment by w568w** [comment]
> 
> 
> What is this error caused by?
> 
> If it's too hard to switch themes on-the-fly (due to widget reloads etc.), maybe we can save user's theme preferences in `SharedPreferences` and set it using `initialPlatform` on application launch.

That's a better solution.

**Comment by kavinzhao** [comment]
> > What is this error caused by?
> > If it's too hard to switch themes on-the-fly (due to widget reloads etc.), maybe we can save user's theme preferences in `SharedPreferences` and set it using `initialPlatform` on application launch.
> 
> That's a better solution.
Actually, we will support both ;)
