### ISSUE TITLE
课表显示问题

### ISSUE THREAD

**Issue by ivanfei-1** [w568w/DanXi#24]
**Describe the bug**
有的课程会显示代码，影响观看

**Screenshots**
![image](https://user-images.githubusercontent.com/67986259/114809400-b29e0b00-9ddc-11eb-904a-890bf32e705e.png)
![image](https://user-images.githubusercontent.com/67986259/114809415-baf64600-9ddc-11eb-8a22-a1184cbd51e2.png)
**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - Version 4月14日版本

**Comment by w568w** [comment]
Work on it very soon.
